### PR TITLE
Replace sound effects with Half-Life 1 ones

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added the technobabble emote, which makes a special sound if you're wearing the scientist labcoat
add: Added a tie to the scientists starting outfit. You will wear it.
add: Added a different scientist starting uniform. Sprited by Fantastic Fwoosh and Mr Epic Sax. Thank you kings.
add: Changed the scientist labcoat to an older one that looks better.
add: The HEV Suit, sprited by Mr. Epic Sax. Thank you king.
tweak: Replaced the researcher's hardsuit with the HEV Suit.
soundadd: Changed soundeffect for stepping on normal tiles or metal ones with the classic HL1 one. Grass, sand and wood are unchanged.
soundadd: Added sounds to most buttons, also from HL1
soundadd: Added two other sounds for triggering the grenade, from the HECU grunts
soundadd: Changed the voting start sound to G-Man telling you to choose
soundadd: Changed the forge Hammer sounds.
soundadd: Added a sound for light switches.
sounddel: removed catwalk1-5.ogg because I was unable to find where they were used in code
/:cl:

## About The Pull Request
I reckon this needs a testmerge first, they might be too loud or too quiet.

## Why It's Good For The Game
FORGET ABOUT FREEMAN

### CODE REVIEW

**Comment by Punkinguy** [comment]
+1 ultra bazat

**Comment by MrEpicSax** [comment]
+1

**Comment by QuarianCommando** [comment]
+2

**Comment by karmaisblackandbluepilled** [comment]
Discord_dhjuauMsYE

**Comment by Zyzarda** [comment]
this isn't what i conceived reeeeee

**Comment by carlopault** [comment]
+2 testmerge it

**Comment by karmaisblackandbluepilled** [comment]
ok

**Comment by karmaisblackandbluepilled** [comment]
what what the hell is modularization again

**Comment by karmaisblackandbluepilled** [comment]
wait why would we ever merge tg code, merges are bad

**Comment by karmaisblackandbluepilled** [comment]
I done my best, if you want something different you gotta tell me what directly, I don't know anything else.

**Pull request closed without merging**
